"""Shared domain enums."""

import enum


class UserRole(str, enum.Enum):
    ADMIN = "ADMIN"
    USER = "USER"


class RegistrationStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    SUSPENDED = "SUSPENDED"
    UNKNOWN = "UNKNOWN"


class ProjectStatus(str, enum.Enum):
    COMPLETED = "COMPLETED"
    ONGOING = "ONGOING"
    CANCELLED = "CANCELLED"
    UNKNOWN = "UNKNOWN"


class OwnershipType(str, enum.Enum):
    OWNED = "OWNED"
    LEASED = "LEASED"
    RENTED = "RENTED"
    OTHER = "OTHER"


class DocumentEntityType(str, enum.Enum):
    COMPANY = "COMPANY"
    REGISTRATION = "REGISTRATION"
    CONTRACTOR_REGISTRATION = "CONTRACTOR_REGISTRATION"
    FINANCIAL_RECORD = "FINANCIAL_RECORD"
    EXPERIENCE = "EXPERIENCE"
    MACHINERY = "MACHINERY"
    PERSONNEL = "PERSONNEL"
    OTHER = "OTHER"


class DocumentStatus(str, enum.Enum):
    VALID = "VALID"
    EXPIRING_SOON = "EXPIRING_SOON"
    EXPIRED = "EXPIRED"
    UNKNOWN = "UNKNOWN"


class FinancialRecordType(str, enum.Enum):
    TURNOVER = "TURNOVER"
    SOLVENCY = "SOLVENCY"
    NET_WORTH = "NET_WORTH"
    FINANCIAL_CAPACITY = "FINANCIAL_CAPACITY"
    OTHER = "OTHER"


class TenderSourceType(str, enum.Enum):
    GOVERNMENT_PORTAL = "GOVERNMENT_PORTAL"
    API = "API"
    PUBLIC_DATA = "PUBLIC_DATA"
    OTHER = "OTHER"


class CollectionMethod(str, enum.Enum):
    HTTP = "HTTP"
    API = "API"
    HTML = "HTML"
    DOCUMENT = "DOCUMENT"
    OTHER = "OTHER"


class CollectionJobStatus(str, enum.Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class SourceHealthStatus(str, enum.Enum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"


class CollectionEventLevel(str, enum.Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"


class CollectionErrorType(str, enum.Enum):
    NETWORK = "NETWORK"
    TIMEOUT = "TIMEOUT"
    HTTP = "HTTP"
    PARSING = "PARSING"
    VALIDATION = "VALIDATION"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    UNEXPECTED = "UNEXPECTED"


class TenderStatus(str, enum.Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
    AWARDED = "AWARDED"
    UNKNOWN = "UNKNOWN"


class IndianStateCode(str, enum.Enum):
    UTTAR_PRADESH = "UTTAR_PRADESH"
    MADHYA_PRADESH = "MADHYA_PRADESH"
    UNKNOWN = "UNKNOWN"


class NormalizationStatus(str, enum.Enum):
    NOT_PROCESSED = "NOT_PROCESSED"
    NORMALIZED = "NORMALIZED"
    FAILED = "FAILED"
    NEEDS_REVIEW = "NEEDS_REVIEW"


class DuplicateMatchType(str, enum.Enum):
    EXACT_DUPLICATE = "EXACT_DUPLICATE"
    LIKELY_DUPLICATE = "LIKELY_DUPLICATE"
    POSSIBLE_DUPLICATE = "POSSIBLE_DUPLICATE"
    NOT_DUPLICATE = "NOT_DUPLICATE"


class DuplicateReviewStatus(str, enum.Enum):
    PENDING = "PENDING"
    CONFIRMED_DUPLICATE = "CONFIRMED_DUPLICATE"
    NOT_DUPLICATE = "NOT_DUPLICATE"
    IGNORED = "IGNORED"


class TenderDocumentDownloadStatus(str, enum.Enum):
    DISCOVERED = "DISCOVERED"
    DOWNLOAD_QUEUED = "DOWNLOAD_QUEUED"
    DOWNLOADING = "DOWNLOADING"
    DOWNLOADED = "DOWNLOADED"
    DOWNLOAD_FAILED = "DOWNLOAD_FAILED"
    ACCESS_RESTRICTED = "ACCESS_RESTRICTED"


class TenderDocumentProcessingStatus(str, enum.Enum):
    PENDING = "PENDING"
    VALIDATED = "VALIDATED"
    INVALID = "INVALID"
    PROCESSING_FAILED = "PROCESSING_FAILED"
    UNSUPPORTED = "UNSUPPORTED"


class TenderDocumentExtractionStatus(str, enum.Enum):
    NOT_EXTRACTED = "NOT_EXTRACTED"
    TEXT_EXTRACTED = "TEXT_EXTRACTED"
    OCR_REQUIRED = "OCR_REQUIRED"
    OCR_COMPLETED = "OCR_COMPLETED"
    EXTRACTION_FAILED = "EXTRACTION_FAILED"


class TenderDocumentExtractionMethod(str, enum.Enum):
    NONE = "NONE"
    DIRECT_EXTRACTION = "DIRECT_EXTRACTION"
    OCR = "OCR"


class TenderDocumentClassification(str, enum.Enum):
    NIT = "NIT"
    BOQ = "BOQ"
    TENDER_DOCUMENT = "TENDER_DOCUMENT"
    TERMS_AND_CONDITIONS = "TERMS_AND_CONDITIONS"
    ELIGIBILITY_DOCUMENT = "ELIGIBILITY_DOCUMENT"
    DRAWING = "DRAWING"
    CORRIGENDUM = "CORRIGENDUM"
    ADDENDUM = "ADDENDUM"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"


class TenderDocumentErrorCode(str, enum.Enum):
    NETWORK_ERROR = "NETWORK_ERROR"
    TIMEOUT = "TIMEOUT"
    HTTP_ERROR = "HTTP_ERROR"
    ACCESS_RESTRICTED = "ACCESS_RESTRICTED"
    INVALID_FILE = "INVALID_FILE"
    UNSUPPORTED_FILE = "UNSUPPORTED_FILE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    PARSE_ERROR = "PARSE_ERROR"
    OCR_ERROR = "OCR_ERROR"
    STORAGE_ERROR = "STORAGE_ERROR"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"


class TenderDocumentProcessingJobStatus(str, enum.Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class TenderDocumentProcessingEventKind(str, enum.Enum):
    DOCUMENT_DISCOVERED = "DOCUMENT_DISCOVERED"
    DOWNLOAD_STARTED = "DOWNLOAD_STARTED"
    DOWNLOAD_COMPLETED = "DOWNLOAD_COMPLETED"
    DOWNLOAD_FAILED = "DOWNLOAD_FAILED"
    FILE_VALIDATED = "FILE_VALIDATED"
    FILE_REJECTED = "FILE_REJECTED"
    TEXT_EXTRACTION_STARTED = "TEXT_EXTRACTION_STARTED"
    TEXT_EXTRACTION_COMPLETED = "TEXT_EXTRACTION_COMPLETED"
    OCR_STARTED = "OCR_STARTED"
    OCR_COMPLETED = "OCR_COMPLETED"
    PROCESSING_COMPLETED = "PROCESSING_COMPLETED"
    PROCESSING_FAILED = "PROCESSING_FAILED"
